<Component type="nexj.core.rpc.http.CharacterStreamHTTPServer" activation="context"
   description="The JSON RPC HTTP server">
   <Properties>
      <Property name="type">JSON</Property>
      <Property name="bufferSize">8192</Property>
      <Property name="contentType">application/json</Property>
      <Property name="maxRequestSize" override="httpMaxSize">0</Property>
      <Property name="server">Server.JSON</Property>
      <Property name="RPCEnabled" override="authRPC">true</Property>
      <Property name="trustedCertificate" override="trust"/>
      <Property name="RPCServer">true</Property>
      <Property name="anonEnabled" override="anonRPC"/>
   </Properties>
</Component>
