-- Creation script for JBoss v4 specific tables.
-- This script is based on JBoss hsqldb-jdbc-state-service.xml, distributed under LGPL.
-- See http://www.jboss.org for JBoss source code.

CREATE TABLE JMS_USERS (
   USERID VARCHAR(32) NOT NULL,
   PASSWD VARCHAR(32) NOT NULL,
   CLIENTID VARCHAR(128),
   PRIMARY KEY(USERID)
);
GRANT ALL ON JMS_USERS TO njdbuser;

CREATE TABLE JMS_ROLES (
   ROLEID VARCHAR(32) NOT NULL,
   USERID VARCHAR(32) NOT NULL,
   PRIMARY KEY(USERID, ROLEID)
);
GRANT ALL ON JMS_ROLES TO njdbuser;

CREATE TABLE JMS_SUBSCRIPTIONS (
   CLIENTID VARCHAR(128) NOT NULL,
   SUBNAME VARCHAR(128) NOT NULL,
   TOPIC VARCHAR(255) NOT NULL,
   SELECTOR VARCHAR(255),
   PRIMARY KEY(CLIENTID, SUBNAME)
);
GRANT ALL ON JMS_SUBSCRIPTIONS TO njdbuser;

CREATE TABLE JMS_MESSAGES(
   MESSAGEID INT NOT NULL,
   DESTINATION VARCHAR(255) NOT NULL,
   TXID INTEGER,
   TXOP CHAR(1),
   MESSAGEBLOB lo,
   PRIMARY KEY (MESSAGEID, DESTINATION)
);
GRANT ALL ON JMS_MESSAGES TO njdbuser;

CREATE INDEX JMS_MESSAGES_TXOP_TXID ON JMS_MESSAGES(TXOP, TXID);
CREATE INDEX JMS_MESSAGES_DESTINATION ON JMS_MESSAGES(DESTINATION);

CREATE TABLE JMS_TRANSACTIONS(TXID INT NOT NULL);
GRANT ALL ON JMS_TRANSACTIONS TO njdbuser;
