-- Creation script for JBoss v4 specific tables.
-- This script is based on JBoss hsqldb-jdbc-state-service.xml, distributed under LGPL.
-- See http://www.jboss.org for JBoss source code.

CREATE TABLE nexj.JMS_USERS (
   USERID VARCHAR(32) NOT NULL,
   PASSWD VARCHAR(32) NOT NULL,
   CLIENTID VARCHAR(128),
   PRIMARY KEY(USERID)
) ENGINE=InnoDB CHARACTER SET=utf8;
GRANT ALL ON nexj.JMS_USERS TO nexj;

CREATE TABLE nexj.JMS_ROLES (
   ROLEID VARCHAR(32) NOT NULL,
   USERID VARCHAR(32) NOT NULL,
   PRIMARY KEY(USERID, ROLEID)
) ENGINE=InnoDB CHARACTER SET=utf8;
GRANT ALL ON nexj.JMS_ROLES TO nexj;

CREATE TABLE nexj.JMS_SUBSCRIPTIONS (
   CLIENTID VARCHAR(128) NOT NULL,
   SUBNAME VARCHAR(128) NOT NULL,
   TOPIC VARCHAR(255) NOT NULL,
   SELECTOR VARCHAR(255),
   PRIMARY KEY(CLIENTID, SUBNAME)
) ENGINE=InnoDB CHARACTER SET=utf8;
GRANT ALL ON nexj.JMS_SUBSCRIPTIONS TO nexj;

CREATE TABLE nexj.JMS_MESSAGES(
   MESSAGEID BIGINT NOT NULL,
   DESTINATION VARCHAR(255) NOT NULL,
   TXID BIGINT,
   TXOP CHAR(1),
   MESSAGEBLOB BLOB,
   PRIMARY KEY (MESSAGEID, DESTINATION)
) ENGINE=InnoDB CHARACTER SET=utf8;
GRANT ALL ON nexj.JMS_MESSAGES TO nexj;

CREATE INDEX JMS_MESSAGES_TXOP_TXID ON nexj.JMS_MESSAGES(TXOP, TXID);
CREATE INDEX JMS_MESSAGES_DESTINATION ON nexj.JMS_MESSAGES(DESTINATION);

CREATE TABLE nexj.JMS_TRANSACTIONS(TXID BIGINT NOT NULL) ENGINE=InnoDB CHARACTER SET=utf8;
GRANT ALL ON nexj.JMS_TRANSACTIONS TO nexj;
