//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace NexJ {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServerSoapBinding", Namespace="http://www.nexjsystems.com/xml-soap")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Exception))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Invocation))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Function))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ByteVector))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PrivilegeSet))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Expression))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Symbol))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(StringId))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Array))]
    public partial class GenericServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback invokeOperationCompleted;
        
        /// <remarks/>
        public GenericServer() {
            this.Url = "http://localhost:7080/nexj/soap";
        }
        
        /// <remarks/>
        public event invokeCompletedEventHandler invokeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("Server#invoke", RequestNamespace="http://www.nexjsystems.com/xml-soap", ResponseNamespace="http://www.nexjsystems.com/xml-soap")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public Response invoke(Request request) {
            object[] results = this.Invoke("invoke", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begininvoke(Request request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("invoke", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response Endinvoke(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void invokeAsync(Request request) {
            this.invokeAsync(request, null);
        }
        
        /// <remarks/>
        public void invokeAsync(Request request, object userState) {
            if ((this.invokeOperationCompleted == null)) {
                this.invokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvokeOperationCompleted);
            }
            this.InvokeAsync("invoke", new object[] {
                        request}, this.invokeOperationCompleted, userState);
        }
        
        private void OninvokeOperationCompleted(object arg) {
            if ((this.invokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invokeCompleted(this, new invokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Request {
        
        /// <remarks/>
        public string @namespace;
        
        /// <remarks/>
        public string version;
        
        /// <remarks/>
        public bool async;
        
        /// <remarks/>
        public bool commit;
        
        /// <remarks/>
        public Locale locale;
        
        /// <remarks/>
        public TimeZone timeZone;
        
        /// <remarks/>
        public TransferObject correlator;
        
        /// <remarks/>
        public Invocation[] invocations;
        
        /// <remarks/>
        public TransferObject[] filters;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Locale {
        
        /// <remarks/>
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Exception {
        
        /// <remarks/>
        public string errorCode;
        
        /// <remarks/>
        public string errorMessage;
        
        /// <remarks/>
        public object[] errorArgs;
        
        /// <remarks/>
        public string @class;
        
        /// <remarks/>
        public OID oid;
        
        /// <remarks/>
        public int ordinal;
        
        /// <remarks/>
        public string[] attributes;
        
        /// <remarks/>
        public Exception[] attributeExceptions;
        
        /// <remarks/>
        public Exception[] exceptions;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class OID {
        
        /// <remarks/>
        public object[] values;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Response {
        
        /// <remarks/>
        public object[] results;
        
        /// <remarks/>
        public TransferObject[][] events;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class TransferObject {
        
        /// <remarks/>
        public string @class;
        
        /// <remarks/>
        public string @event;
        
        /// <remarks/>
        public int version;
        
        /// <remarks/>
        public OID oid;
        
        /// <remarks/>
        public string[] keys;
        
        /// <remarks/>
        public object[] values;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Invocation {
        
        /// <remarks/>
        public TransferObject @object;
        
        /// <remarks/>
        public string @event;
        
        /// <remarks/>
        public object[] arguments;
        
        /// <remarks/>
        public Pair attributes;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Pair {
        
        /// <remarks/>
        public object head;
        
        /// <remarks/>
        public object tail;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Macro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Function {
        
        /// <remarks/>
        public ushort[] code;
        
        /// <remarks/>
        public object[] constants;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Macro : Function {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class ByteVector {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class PrivilegeSet {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] mask;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Expression {
        
        /// <remarks/>
        public string text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Symbol {
        
        /// <remarks/>
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class StringId {
        
        /// <remarks/>
        public string id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class Array {
        
        /// <remarks/>
        public object[] items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.nexjsystems.com/xml-soap")]
    public partial class TimeZone {
        
        /// <remarks/>
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void invokeCompletedEventHandler(object sender, invokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}
