'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'
Namespace NexJ
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServerSoapBinding", [Namespace]:="http://www.nexjsystems.com/xml-soap"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Exception)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Invocation)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType([Function])),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ByteVector)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(PrivilegeSet)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Expression)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Symbol)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(StringId)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Array))>  _
    Partial Public Class GenericServer
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private invokeOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost:7080/nexj/soap"
        End Sub
        
        '''<remarks/>
        Public Event invokeCompleted As invokeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("Server#invoke", RequestNamespace:="http://www.nexjsystems.com/xml-soap", ResponseNamespace:="http://www.nexjsystems.com/xml-soap")>  _
        Public Shadows Function invoke(ByVal request As Request) As <System.Xml.Serialization.SoapElementAttribute("response")> Response
            Dim results() As Object = MyBase.Invoke("invoke", New Object() {request})
            Return CType(results(0),Response)
        End Function
        
        '''<remarks/>
        Public Shadows Function Begininvoke(ByVal request As Request, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return MyBase.BeginInvoke("invoke", New Object() {request}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Shadows Function Endinvoke(ByVal asyncResult As System.IAsyncResult) As Response
            Dim results() As Object = MyBase.EndInvoke(asyncResult)
            Return CType(results(0),Response)
        End Function
        
        '''<remarks/>
        Public Overloads Sub invokeAsync(ByVal request As Request)
            Me.invokeAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub invokeAsync(ByVal request As Request, ByVal userState As Object)
            If (Me.invokeOperationCompleted Is Nothing) Then
                Me.invokeOperationCompleted = AddressOf Me.OninvokeOperationCompleted
            End If
            Me.InvokeAsync("invoke", New Object() {request}, Me.invokeOperationCompleted, userState)
        End Sub
        
        Private Sub OninvokeOperationCompleted(ByVal arg As Object)
            If (Not (Me.invokeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent invokeCompleted(Me, New invokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Request
        
        '''<remarks/>
        Public [namespace] As String
        
        '''<remarks/>
        Public version As String
        
        '''<remarks/>
        Public async As Boolean
        
        '''<remarks/>
        Public commit As Boolean
        
        '''<remarks/>
        Public locale As Locale
        
        '''<remarks/>
        Public timeZone As TimeZone
        
        '''<remarks/>
        Public correlator As TransferObject
        
        '''<remarks/>
        Public invocations() As Invocation
        
        '''<remarks/>
        Public filters() As TransferObject
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Locale
        
        '''<remarks/>
        Public name As String
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Exception
        
        '''<remarks/>
        Public errorCode As String
        
        '''<remarks/>
        Public errorMessage As String
        
        '''<remarks/>
        Public errorArgs() As Object
        
        '''<remarks/>
        Public [class] As String
        
        '''<remarks/>
        Public oid As OID
        
        '''<remarks/>
        Public ordinal As Integer
        
        '''<remarks/>
        Public attributes() As String
        
        '''<remarks/>
        Public attributeExceptions() As Exception
        
        '''<remarks/>
        Public exceptions() As Exception
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class OID
        
        '''<remarks/>
        Public values() As Object
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Response
        
        '''<remarks/>
        Public results() As Object
        
        '''<remarks/>
        Public events()() As TransferObject
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class TransferObject
        
        '''<remarks/>
        Public [class] As String
        
        '''<remarks/>
        Public [event] As String
        
        '''<remarks/>
        Public version As Integer
        
        '''<remarks/>
        Public oid As OID
        
        '''<remarks/>
        Public keys() As String
        
        '''<remarks/>
        Public values() As Object
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Invocation
        
        '''<remarks/>
        Public [object] As TransferObject
        
        '''<remarks/>
        Public [event] As String
        
        '''<remarks/>
        Public arguments() As Object
        
        '''<remarks/>
        Public attributes As Pair
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Pair
        
        '''<remarks/>
        Public head As Object
        
        '''<remarks/>
        Public tail As Object
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.SoapIncludeAttribute(GetType(Macro)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class [Function]
        
        '''<remarks/>
        Public code() As UShort
        
        '''<remarks/>
        Public constants() As Object
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Macro
        Inherits [Function]
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class ByteVector
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public value() As Byte
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class PrivilegeSet
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public mask() As Byte
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Expression
        
        '''<remarks/>
        Public text As String
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Symbol
        
        '''<remarks/>
        Public name As String
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class StringId
        
        '''<remarks/>
        Public id As String
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class Array
        
        '''<remarks/>
        Public items() As Object
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.nexjsystems.com/xml-soap")>  _
    Partial Public Class TimeZone
        
        '''<remarks/>
        Public name As String
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")>  _
    Public Delegate Sub invokeCompletedEventHandler(ByVal sender As Object, ByVal e As invokeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class invokeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Response
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Response)
            End Get
        End Property
    End Class
End Namespace
